### ISSUE TITLE
OSX - Bug - #include "ui_importimages.h"

### ISSUE THREAD

**Issue by MarcTux** [OpenPIV/openpiv-c--qt#8]
#include "ui_importimages.h" is not found during compil.
assume the new architecture would lead to #include "ui/importimages.ui" but then <? xml> is not handled has valid argument.
Any thoughts?
Thanks!

**Comment by timdewhirst** [comment]
Thanks for the report. Could you detail the compilation steps and version of Qt that led to this error, starting from a clean tree. Thanks!

**Comment by MarcTux** [comment]
Thanks timdewhirst for the quick feedback!

I am trying to compile on OS X 10.11.5 (elCapitan) w/ QT 4.0.0 (based on Qt 5.6.0 (Clang 7.0 (Apple), 64 bit)), and Clang as compiler.
Error comes here:
``batchwindow.h:33: erreur : 'ui_batchwindow.h' file not found
#include `"ui_batchwindow.h"`

**Comment by timdewhirst** [comment]
I suspect the problem is that you've not run qmake before make. When you run qmake a tool called uic is run against the .ui files in the ui/ directory, and this produces a header called e.g. ui_batchwindow.h.

Try running qmake followed by make; if this doesn't resolve the issue let me know.

Thanks!

**Comment by MarcTux** [comment]
No I do call qmake before calling make in my compile sequences. But I get an error I did not think critical as it tells me that qmake ended up correctly :
`Débute : "/Users/**/Qt/5.6/clang_64/bin/qmake" /Users/**/Documents/OPENPIV/openpiv-c--qt-master/openpiv-c++.pro -r -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
RCC: Warning: No resources in '../openpiv-c--qt-master/share/images/images.qrc'.`

`Starting : "/usr/bin/make" `
...
`In file included from ../openpiv-c--qt-master/src/main.cpp:28:
In file included from ../openpiv-c--qt-master/src/mainwindow.h:39:
In file included from ../openpiv-c--qt-master/src/session.h:37:
In file included from ../openpiv-c--qt-master/src/processing.h:49:
../openpiv-c--qt-master/src/batchwindow.h:33:10: fatal error: 'ui_batchwindow.h' file not found
#include "ui_batchwindow.h"
         ^
1 error generated.
make: *** [_build/main.o] Error 1`

**Comment by timdewhirst** [comment]
Next steps: can you:

 * run find . -iname "ui_" from within the root source directory and paste the results
 * check the contents of the generated makefile; it should contain a line starting INCPATH like:

INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I. -Isrc -I.moc -I.ui

 * check when the makefile was last modified i.e. is it up to date?
Thanks!

**Comment by MarcTux** [comment]
Thanks for helping Timdewhirst!
so:
> run find . -iname "ui_" from within the root source directory and paste the results
  I got nothing

> check the contents of the generated makefile; it should contain a line starting INCPATH like:
it is, please find here;
`INCPATH       = -I../openpiv-c--qt-master -I. -I../openpiv-c--qt-master -I../openpiv-c--qt-master/src -I/usr/local/include -I/usr/local/include -I../../../Qt/5.6/clang_64/lib/QtGui.framework/Headers -I../../../Qt/5.6/clang_64/lib/QtXml.framework/Headers -I../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers -I_build -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../../Qt/5.6/clang_64/mkspecs/macx-clang -F/Users/**/Qt/5.6/clang_64/lib`

> check when the makefile was last modified i.e. is it up to date?
brand new, just delete the _build file after compile to make sure I generate all new files everytime

**Comment by timdewhirst** [comment]
Typo on my behalf: that should have been find . -iname "ui_*"

Which directory are you running qmake in? It looks like you're in a sub-directory of the main directory; could you execute qmake and make in the source root directory.

Thanks!

**Comment by MarcTux** [comment]
I am running `find . -iname "ui_*"` from the directory where `openpiv-c++.pro` is located which should be the root, right?

From there at least it gives me nothing more!

Thanks!

**Comment by MarcTux** [comment]
Actually, I am using QTCreator which creates a different directory for the compile output.

But using the terminal and going through `qmake` and `make` gives no difference unfortunately.

**Comment by timdewhirst** [comment]
openpiv-c++.pro is in the root, correct.

I don't have a mac to try and reproduce this on, hence the game of 20 questions :)

As you mentioned QtCreator, could you check to see if openpiv-c++.pro has some local modifications that may be causing this problem: git status in the root directory should show you (assuming you've got the code using git clone).

**Comment by MarcTux** [comment]
Hi Timdewhirst,
No worries, I am curious to understand why it does not work as well and I appreciate your time and help.

I do have clone the repo using git, here is the status:
`	modified:   fftw.pri
	modified:   libtiff.pri
	modified:   src/imagelist.h
	modified:   src/imagepaint.h
	modified:   src/importimagelist.h
	modified:   src/importimages.h
	modified:   src/itempaint.h
	modified:   src/main.cpp
	modified:   src/mainwindow.h
	modified:   src/pivdisplay.h
	modified:   src/vectorlist.h`

But no modif on the `.pro`.

I also tried to compile using the terminal but it gives me back the same errors...

**Comment by timdewhirst** [comment]
Right; let's press on :)

* could you tell me the version of qmake: qmake --version 

The generated makefile should have a line like: 

INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I. -Isrc -I_build -I_build

The important part is -I_build, and this comes from UI_DIR =  _build in the openpiv-c++.pro file.

When you run make you should see a line like this: 

/usr/lib/x86_64-linux-gnu/qt4/bin/uic ui/mainwindow.ui -o _build/ui_mainwindow.h
/usr/lib/x86_64-linux-gnu/qt4/bin/uic ui/importimages.ui -o _build/ui_importimages.h
/usr/lib/x86_64-linux-gnu/qt4/bin/uic ui/batchwindow.ui -o _build/ui_batchwindow.h

This shows that uic is being run against the three .ui files and their output is placed in _build/.

Could you check that these steps are being followed; this should hopefully help us narrow down the issue!

Thanks!

**Comment by dragoncambodia** [comment]
Hello.
I create qt project and get cpp and h files.
And then using cmake-gui I made Xcode project and then trying to build it.
Error "'ui_aboutus.h' file not found. "
I did this for windows and it worked well.
Please tell me why?

**Comment by alexlib** [comment]
@dragoncambodia please try now, I merged the pull request from @timdewhirst

**Comment by timdewhirst** [comment]
closing as this code had been replaced.
